TT#37401 Fix 50ecc1544: depends on netcat-openbsd since we use 'nc -U' (not available in 'netcat-traditional')
Upgrade mr6.3->mr6.4 failed with error:
> 2018-06-03 15:39:13: [35/47] Running: /usr/share/ngcp-upgrade/steps/2.8/ngcpcfg_build /etc/mysql/ /etc/systemd/
> Building ngcpcfg config files: /etc/mysql/ /etc/systemd/
> 2018-06-03 15:39:13: configs were checked successfuly
> 2018-06-03 15:39:14: No patchtt files found, nothing to patch.
> netcat: invalid option -- 'U'
> nc -h for help
> 2018-06-03 15:39:14: Error: tt2-daemon cannot load /etc/ngcp-config/config.yml:
> netcat: invalid option -- 'U'
> nc -h for help
> ERROR: the step '2.8/ngcpcfg_build' failed, upgrade aborted!

Change-Id: I9d5d469276c80ff961c77ab70bd07490bc5f34b3