TT#171400 Build-Depend on recent python3 version
Path.is_relative() (as used in t/fixtures/programs.py) is a new feature
as of Python 3.9, see
https://docs.python.org/3.9/whatsnew/changelog.html?highlight=is_relative_to
and https://github.com/python/cpython/issues/81870

When running with an older python3 version, tests fail with:

| env = {}
|
|     def prepare_conf(env={}):
|         testenv = define_env(env)
|         ngcpcfg_path = testenv["NGCPCFG"]
| >       if not ngcpcfg_path.is_relative_to(CWD):
| E       AttributeError: 'PosixPath' object has no attribute 'is_relative_to'

While python3-pytest depends on python3:any, let's keep the build
dependency slim, by build-depending on the python3-minimal package only.

Problem spotted while trying to debug the git safe.directory issue
in an outdated bullseye based container, providing python3 3.7.5-3.

Change-Id: Ib620a796a780817a81a51d791a766c950b1a541c