MT#19043 Add env var SKIP_NGCP_FUNCTIONS to helper restore-permissions
During the installation we need an ability to fix perms the first time
on PRO sp2 installation. The file /etc/ngcp-config/config.yml is not
available at the moment causing function "main" failed on load:
> /usr/share/ngcp-ngcpcfg/helper/restore-permissions /tmp/tmp.Hrt0sBRYy3
> Error: Configuration file /etc/ngcp-config/config.yml does not exist (unconfigured?) - exiting.

Change-Id: Ieb196690246d7c1ea59e7f4359d72179472c278b