MT#15261 Allow using symbolic links for YML files
    At the moment it is impossible to use symbolic links for YML files.
    The following error happens:
    > root@spce:/etc/ngcp-config# ngcpcfg apply
    > Error: Encoding check of /etc/ngcp-config/config.spce.yml fails: neither ASCII nor UTF-8.
    > Error: Please convert /etc/ngcp-config/config.spce.yml to UTF-8.
    >
    > NOTE:
    > * Check encoding via:
    > # file /etc/ngcp-config/config.spce.yml
    > * To convert ISO-8859/latin1 to UTF-8 execute:
    > # iconv -f latin1 -t utf8 < /etc/ngcp-config/config.spce.yml > /etc/ngcp-config/config.spce.yml.tmp \
    > && mv /etc/ngcp-config/config.spce.yml.tmp /etc/ngcp-config/config.spce.yml

    As a result the following usecase ('node-type' specific file) failed:
    > >>> ls -la /etc/ngcp-config/*
    > total 72
    > drwxr-xr-x 2 root root  4096 Sep 18 13:57 .
    > drwxr-xr-x 6 root root  4096 Sep 16 23:34 ..
    > lrwxrwxrwx 1 root root    15 Sep 18 13:57 config.db01a.yml -> ./config.db.yml
    > lrwxrwxrwx 1 root root    15 Sep 18 13:57 config.db01b.yml -> ./config.db.yml
    > -rw-r--r-- 1 root root   224 Sep 18 12:43 config.db.yml
    > -rw-r--r-- 1 root root   250 Sep 18 12:34 config.lb.yml
    > -rw-r--r-- 1 root root   146 Sep 18 12:44 config.mgmt.yml
    > -rw-r--r-- 1 root root   251 Sep 18 13:56 config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx01a.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx01b.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx02a.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx02b.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx03a.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx03b.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx04a.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx04b.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx05a.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    18 Sep 18 13:57 config.prx05b.yml -> ./config.proxy.yml
    > lrwxrwxrwx 1 root root    15 Sep 18 13:57 config.slb01a.yml -> ./config.lb.yml
    > lrwxrwxrwx 1 root root    15 Sep 18 13:57 config.slb01b.yml -> ./config.lb.yml
    > lrwxrwxrwx 1 root root    17 Sep 18 13:57 config.web01a.yml -> ./config.mgmt.yml
    > lrwxrwxrwx 1 root root    17 Sep 18 13:57 config.web01b.yml -> ./config.mgmt.yml
    > -rw-r--r-- 1 root root 13051 Sep 18 12:54 config.yml
    > -rw-r--r-- 1 root root  4633 Sep 15 16:13 constants.yml
    > -rw-r--r-- 1 root root 16534 Sep 15 16:09 network.yml

    > >>> cat config.lb.yml
    > ---
    > checktools:
    >   collcheck:
    >     loadlong: 2
    >     loadmedium: 2
    >     loadshort: 3
    > heartbeat:
    >   pingnodes:
    >     - 1.1.1.1
    >     - 2.2.2.2

    (backported from commit b9d07def2564a55c87f1523cf7e9641812de88fd)

(cherry picked from commit 7156159b63a073de33e9ec5bfc4607b9a9109e0b)

Change-Id: I404554fea956067bc1094d1ebc4dc73c8ceff420